FROM ubuntu:bionic
RUN apt update && apt install -y git cmake 
RUN apt update && apt install -y curl zip unzip tar
RUN apt update && apt install -y ninja-build
RUN apt update && apt install -y build-essential